### ISSUE TITLE
How is this fork different

### ISSUE THREAD

**Issue by duckheadsoftware** [MrSquirrely/DuplaImage.Lib#1]
This is a fork of a library I use, but I can't find any change log, what's better/improved from the original ?

Thanks

**Comment by MrSquirrely** [comment]
At the moment not much currently. I haven't gotten a chance to do some research on other ways to do detection.
All I pretty much did was 
 - clean the code
- Moved the ImageMagickTransformer into it's own library (DuplaImage.Lib.ImageMagick  on nuget)
     so if you don't want to use Image Magick, you don't need to also download the library.
-  Update the ImageMagick Library so it'll work (Which was the original reason I did this as the original developer seems to have disappeared and it wasn't working.)
The links to the nugets are 
 - https://www.nuget.org/packages/DuplaImage.Lib/
 - https://www.nuget.org/packages/DuplaImage.Lib.ImageMagick/
if you needed them.

**Comment by duckheadsoftware** [comment]
Thanks for the work, I'll download and try out yours.

In case you want to look at it, a performance hits using this library is in ImageMagickTransformer.TransformImage, the image is quantized before resize, this takes 4 times longer than resize then quantize. My tests show it has no effect on the hash keys produced (end result).
